#!/usr/bin/env bash

main_configuration=\
"## Syntax name for syntax highlighting
## Only specify names supported by prism.js
## List of supported syntaxes:
### bash c cpp asm6502 java python aspnet csharp cmake django dns-zone docker
### go hcl ignore javadoc json json5 kotlin latex makefile markdown matlab
### mongodb nasm nginx objectivec opencl perl php phpdoc plsql powershell
### processing prolog qml r regex ruby rust scala sql swift typescript
### verilog vhdl vim wasm
#SYNTAX=

## Design pages as you want
### navigation title comment reference source execution input output error pagination
#PAGE_TEMPLATE=\"navigation title comment reference source execution input output error pagination\"
#CHAPTER_TEMPLATE=\"navigation title comment reference pagination toc\"

## Whether source should be compiled
## Set false for scripting languages
#COMPILABLE=true

## Program used to interpret or compile the practice file
#COMPILER=
#COMPILER_OPTIONS=
#GENERATES_COMPILATION_ERROR=false

## Order of statements in compilation command
## Available statements:
### compiler, options, object, source, headers, location, binary, page,
### makefile, stepN optionN, extension-xyz
#COMPILATION_SCHEME=\"compiler options object source\"
#POST_COMPILATION_SCHEME=

## Whether all sources in one line of .index file should appear in linkage
## usually other files are headers only and won't need to be linked to source
#INCLUDES=false

## What is the extension of the object which compiler throws?
## Default is set to .o
#OUTPUT_OBJECT=

## Whether object should be linked after compilation too
## Defaut is set to true
## Set false for scripts
#LINKABLE=true

## Whether linker explicitly specified
## This is only used for compilable sources
#LINKER=
#LINKER_OPTIONS=
#GENERATES_LINKAGE_ERROR=false

## Order of statements in linkage command
## Available statements: linker, options, binary, object, headers, source,
##   location, page
#LINKAGE_SCHEME=\"linker options binary object headers\"

## Wether generated output can run as an executable
#RUNNABLE=true
#RUNNING_OPTIONS=
#GENERATES_RUNTIME_ERROR=false
#CAPTURE_SCREENSHOT=false

## Order of statements in running command
## Available statements: compiler, linker, options, binary, object, headers,
##   source, location, page
#RUNNING_SCHEME=\"binary options\"

## Whether program should be run in the background
## Suitable for servers and services which need to wait for clients to compile
## and respond
## Rationally, servers should be compiled and executed first, then clients
#RUN_IN_BACKGROUND=false

## Terminate program in RUNTIME seconds after exection
## Suitable for servers which will not exit after execution
#TERMINATE=false
#TERMINATION_SIGNAL=SIGTERM
#RUNTIME=3

## Specify the hardness of this chapter
## This feature will be used in Milestone technical courses and tutorials
#TECHNICAL_LEVEL=

## DO NOT EDIT!
#VALIDATION_ID=0"

# terminates script executaion after call
function usage {
	echo "Practice Repository Manager (Milestone)"
	echo
	tput setaf $SEVERITY_HIGH
	echo "Usage:"
	tput sgr0
	echo
	tput setaf 7
	echo "  $ practice-manager <path>"
	tput sgr0
	echo "                        Create a chapter/page, or just peek inside"
	echo
	tput setaf 7
	echo "  $ practice-manager <source> <destination>"
	tput sgr0
	echo "                        Move a chapter/page"
	echo
	tput setaf 7
	echo "  $ practice-manager"
	tput sgr0
	echo "                        Generate html-files, no option required"
	echo
	tput setaf $SEVERITY_HIGH
	echo "Options:"
	tput sgr0
	echo
	echo "  -r <path/to/file>     Remove page or chapter"
	echo "  -o <path/to/file>     Reorder index of page or chapter"
	echo "  -f                    Force compile, regenerates all output files"
	echo
}

SEVERITY_LOW=4
SEVERITY_MEDIUM=3
SEVERITY_HIGH=1

# html line generators
###############################################################################

# requires path to page
# requires begin/end as second parameter
function generate_html_section {
	local page="${1%.*}"
	page="${page##*/}"
	local side="${2:-begin}"
	
	if [ "$side" = "begin" ]
	then
		cat << EOF >> "./html-files/${index}.html"
<!DOCTYPE html>
<html lang="en">
EOF
	else
		cat << EOF >> "./html-files/${index}.html"
</html>
EOF
	fi
}

# required source
# optional side begin/end
function generate_html_head {
	local side="${1:-begin}"
	local page="$2"
	local title=

	if [ "$side" = "begin" ]
	then
		if [ -f "${page%.*}.title.txt" ]
		then
			title="$(cat "${page%.*}.title.txt")"
		else
			tput setaf $SEVERITY_MEDIUM
			echo "title substituted: $page" >&2
			tput sgr0
		fi
	
		cat << EOF >> "./html-files/${index}.html"
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>${title:-"Milestone Practices"}</title>
EOF
	else
		echo "</head>" >> "./html-files/${index}.html"
	fi
}

# requires header size
# requires title
# optional id
function generate_html_header {
	local size="${1:-1}"
	local title="${2:-header}"

	cat << EOF >> "./html-files/${index}.html"
<h${size}>
<a id="${title// /-}" class="anchor" aria-hidden="true" href="#${title// /-}">
<svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true">
<path fill-rule="evenodd" d="M7.775 3.275a.75.75 0 001.06 1.06l1.25-1.25a2 2 0 112.83 2.83l-2.5 2.5a2 2 0 01-2.83 0 .75.75 0 00-1.06 1.06 3.5 3.5 0 004.95 0l2.5-2.5a3.5 3.5 0 00-4.95-4.95l-1.25 1.25zm-4.69 9.64a2 2 0 010-2.83l2.5-2.5a2 2 0 012.83 0 .75.75 0 001.06-1.06 3.5 3.5 0 00-4.95 0l-2.5 2.5a3.5 3.5 0 004.95 4.95l1.25-1.25a.75.75 0 00-1.06-1.06l-1.25 1.25a2 2 0 01-2.83 0z">
</path>
</svg>
${title}
</h${size}>
EOF
}

# requires path to page
# requires header size
# requires title
# requires link
function generate_html_header_with_link {
	local page="${1%.*}"
	page="${page##*/}"
	local size="${2:-1}"
	local title="${3:-header}"
	local link="${4:-#}"

	echo "<h${size}><a href="$link">$title</a></h${size}>" >> "./html-files/${index}.html"
}

# requires begin/end
function generate_html_style {
	case "$1" in
		begin)
			echo "<style>" >> "./html-files/${index}.html"
			;;
		end)
			echo "</style>" >> "./html-files/${index}.html"
			;;
		*)
			tput setaf $SEVERITY_HIGH
			echo "html style tag missed!" >&2
			tput sgr0
			return 1
			;;
	esac
}

# requires css file
function load_css {
	local style="$1"
	local base=milestone-properties/css

	if [ -f "$base/$style" ]
	then
		cat "$base/$style" >> "./html-files/${index}.html"
	else
		tput setaf $SEVERITY_HIGH
		echo "CSS file does not exist: $style" >&2
		tput sgr0
		return 1
	fi
}

# requires begin/end
function generate_html_script {
	case "$1" in
		begin)
			echo "<script>" >> "./html-files/${index}.html"
			;;
		end)
			echo "</script>" >> "./html-files/${index}.html"
			;;
		*)
			tput setaf $SEVERITY_HIGH
			echo "Missing html script tag!" >&2
			tput sgr0
			return 1
			;;
	esac
}

# requires script file
function load_javascript {
	local script="$1"
	local base=milestone-properties/js

	if [ -f $base/$script ]
	then
		cat $base/$script >> "./html-files/${index}.html"
	else
		tput setaf $SEVERITY_HIGH
		echo "Script file not found: $script" >&2
		tput sgr0
		return 1
	fi
}

# requires syntax file
function load_syntax_highlighting {
	local page="$1"
	local syntax="${2:-$SYNTAX.html}"
	local base=milestone-properties/js/syntax

	if [ -z "$syntax" ]
	then
		tput setaf $SEVERITY_HIGH
		echo "Syntax not specified: $page" >&2
		tput sgr0
		return 1
	elif [ -f $base/$syntax ]
	then
		cat $base/$syntax >> "./html-files/${index}.html"
	else
		tput setaf $SEVERITY_HIGH
		echo "Syntax file ${syntax} does not exist: $page" >&2
		tput sgr0
	fi
}

# requires begin/end
function generate_html_body {
	case $1 in
		begin)
			echo "<body class=\"container\">" >> "./html-files/${index}.html"
			;;
		end)
			echo "</body>" >> "./html-files/${index}.html"
			;;
	esac
}

# optional begin/end
# optional pre class
# optional code class
# optional attributes
function generate_html_code {
	local side="${1:-begin}"
	local pre_class="$2"
	local code_class="$3"
	shift 3
	local attributes="$@"
	local code_tag

	if [ -n "$code_class" ]
	then
		code_tag="<code class=\"${code_class}\">"
	else
		code_tag="<code>"
	fi

	if [ "$side" = "begin" ]
	then
		cat << EOF >> "./html-files/${index}.html"
<pre class="${pre_class}" $attributes>
${code_tag}
EOF
	else
		cat << EOF >> "./html-files/${index}.html"
</code>
</pre>
EOF
	fi
}

# requires path to page
# optional begin/end
# optional css style name
# optional multiple attributes
function generate_html_div {
	local page="${1%.*}"
	page="${page##*/}"
	local side="${2:-begin}"
	local css_style="$3"
	local div_tag

	if [ -n "$css_style" ]
	then
		shift 3
		div_tag="<div class=\"${css_style}\" $@>"
	else
		div_tag="<div>"
	fi

	if [ "$side" = "begin" ]
	then
		cat << EOF >> "./html-files/${index}.html"
${div_tag}
EOF
	else
		cat << EOF >> "./html-files/${index}.html"
</div>
EOF
	fi
}

# requires path to page
function generate_html_break {
	echo "<br />" >> "./html-files/${index}.html"
}

function generate_html_breaker {
	echo "<hr />" >> "./html-files/${index}.html"
}

# requires path to page
# requires link
# requires title
# optional css class
function generate_html_link {
	local page="${1%.*}"
	page="${page##*/}"
	local link="${2:-#}"
	local title="${3:-link}"
	local class="$4"

	if [ -n "$class" ]
	then
		echo "<a class=\"${class}\" href=\"$link\">$title</a>" >> "./html-files/${index}.html"
	else
		echo "<a href=\"$link\">$title</a>" >> "./html-files/${index}.html"
	fi
}

# requires path to page
# requies text
# optional command
function generate_html_text {
	local page="$1"
	local text="$2"
	local style="$3"
	local tag=

	if [ -n "$style" ]
	then
		tag="<p class=\"${style}\">"
	else
		tag="<p>"
	fi

	echo "${tag}${text}</p>" >> "./html-files/${index}.html"
}

# optional begin/end
# optional css class
# optional css style
function generate_html_list {
	local side="${1:-begin}"
	local class="$2"
	local style="$3"
	local tag=

	if [ "$side" = "begin" ]
	then
		if [ -n "$class" ]
		then
			if [ -n "$style" ]
			then
				tag="<ul class=\"${class}\" style=\"${style}\">"
			else
				tag="<ul class=\"${class}\">"
			fi
		else
			tag="<ul>"
		fi

		echo "${tag}${text}" >> "./html-files/${index}.html"
	elif [ "$side" = "end" ]
	then
		echo "</ul>" >> "./html-files/${index}.html"
	fi
}

# requires path to page
# optional begin/end
# optional css class
# optional css style
function generate_html_ordered_list {
	local page="$1"
	local side="${2:-begin}"
	local class="$3"
	local style="$4"
	local tag=

	if [ "$side" = "begin" ]
	then
		if [ -n "$class" ]
		then
			if [ -n "$style" ]
			then
				tag="<ol class=\"${class}\" style=\"${style}\">"
			else
				tag="<ol class=\"${class}\">"
			fi
		else
			tag="<ol>"
		fi

		echo "${tag}${text}" >> "./html-files/${index}.html"
	elif [ "$side" = "end" ]
	then
		echo "</ol>" >> "./html-files/${index}.html"
	fi
}

# requires path to page
# optional begin/end
# optional css class
# optional css style
function generate_html_nav {
	local page="$1"
	local side="${2:-begin}"
	local class="$3"
	local tag=

	if [ "$side" = "begin" ]
	then
		if [ -n "$class" ]
		then
			tag="<nav aria-label=\"${class}\">"
		else
			tag="<nav>"
		fi

		echo "${tag}${text}" >> "./html-files/${index}.html"
	elif [ "$side" = "end" ]
	then
		echo "</nav>" >> "./html-files/${index}.html"
	fi
}

# required text
# optional class
# optional multiple attributes
function generate_html_item {
	local text="$1"
	local class="$2"
	local tag=
	local tag_end="</li>"

	if [ -n "$class " ]
	then
		shift 3
		tag="<li class=\"${class}\" $@>"
	else
		tag="<li>"
	fi

	echo "${tag}${text}${tag_end}" >> "./html-files/${index}.html"
}

# requires path to page
# required text
# optional address
# optional class
# optional access key
function generate_html_item_with_link {
	local text="$1"
	local address="$2"
	local class="$3"
	local access_key="$4"
	local access_direction=
	local tag=
	local tag_end="</li>"

	if [ -n "$class " ]
	then
		tag="<li class=\"${class}\">"
	else
		tag="<li>"
	fi

	if [ -n "$address" ]
	then
		if [ -n "$access_key" ]
		then
			tag="${tag}<a title=\"Shortcut: ALT + SHIFT + ${access_key}\" accesskey=\"${access_key}\" href=\"/${address#/}\">"
		else
			tag="${tag}<a href=\"/${address#/}\">"
		fi
		tag_end="</a></li>"
	else
		tag_end="</li>"
	fi

	echo "${tag}${text}${tag_end}" >> "./html-files/${index}.html"
}

# requires path to page
# requires begin/end
function generate_list_group_root {
	local path="$1"
	local side="${2:-begin}"

	generate_html_div "$path" "$side" "list-group list-group-root well"
}

# requires path to page
# requires begin/end
# requires id
function generate_list_group {
	local path="$1"
	local side="${2:-begin}"
	local id="$3"

	generate_html_div "$1" "$side" "list-group collapse" "id=\"${id}\""
}

# requires local link
# requires title
# requires badge
function generate_list_group_collapse_item {
	local link="${1}"
	local title="${2}"
	local badge_counter="${3}"

	cat << EOF >> "./html-files/${index}.html"
<a href="#${link}" class="list-group-item" data-toggle="collapse">
	<i class="glyphicon glyphicon-chevron-right"></i>${title}
	<span class="badge badge-primary badge-pill">${badge_counter}</span>
</a>
EOF
}

# requires local link
# requires title
# requires nest number
# requires badge counter
function generate_list_group_item {
	local link="${1}"
	local title="${2}"
	local badge_counter=
	local classes="list-group-item"

	if [ "$3" -le 1 ]
	then
		classes="${classes} group-child"
	fi

	if [ -n "$4" ]
	then
		badge_counter="<span class=\"badge badge-primary badge-pill\">${4}</span>"
	fi

	cat << EOF >> "./html-files/${index}.html"
<a href="/${link#/}" class="${classes}">
	${title}
	${badge_counter}
</a>
EOF
}

# requires source
# requires image name
# optional line number to set image
function generate_html_image {
	local source="$1"
	local location="${source%/*}"
	local image="$2"
	local image_alias="${page_alias%/*}/${image}"
	local linenumber="$3"
	local alt="${image%.*}"

	if [ -f "${location}/${image}" ]
	then
		cp "${location}/${image}" "./html-files${image_alias#./html-files}"
		if [ -n "$linenumber" ]
		then
			sed -i "${linenumber}a <img class=\"img-responsive\" src=\"${image_alias}\" alt=\"${alt//-/ }\">" "./html-files/${index}.html"
		else
			echo "<img class=\"img-responsive\" src=\"${image_alias}\" alt=\"${alt//-/ }\">" >> "./html-files/${index}.html"
		fi
	else
		echo "<b>Image Not Found</b>" >> "./html-files/${index}.html"
		tput setaf $SEVERITY_HIGH
		echo "image not found: $source"
		tput sgr0
		return 1
	fi
}

# requires source
function generate_html_screenshot {
	local source="$1"
	local image="${source%.*}.screenshot.png"
	local image_alias="${page_alias}.screenshot.png"

	if [ -f "$image" ]
	then
		cp "$image" "./html-files${image_alias#./html-files}"
		echo "<img class=\"img-responsive\" src=\"${image_alias}\" alt=\"${source##*/} Screenshot\">" >> "./html-files/${index}.html"
		tput setaf $SEVERITY_LOW
		echo "screenshot linked: $page_alias"
		tput sgr0
	else
		echo "<b>Screenshot Not Found</b>" >> "./html-files/${index}.html"
		tput setaf $SEVERITY_HIGH
		echo "image not found: $source"
		tput sgr0
		return 1
	fi
}

# required functions for managing practice pages
###############################################################################

# requires path to page
function extract_configuration {
	if [ -f "${1%.*}.config" ]
	then
		sed -i 's/^#\([^#]\)/\1/' "${1%.*}.config"
	fi
}

# requires absolute path to page
function generate_configuration {
	local page

	if [ -f "$1" ]
	then
		page="${1%.*}.config"
	elif [ -d "$1" ]
	then
		page="${1%/}/.config"
	else
		tput setaf $SEVERITY_HIGH
		echo "invalid location to create config file: $1" >&2
		tput sgr0
		return 1
	fi

	cat << EOF > "$page"
$main_configuration
EOF
}

# requires path to config
function regenerate_configuration {
	if [ "${1##*.}" != "config" ]
	then
		tput setaf $SEVERITY_HIGH
		echo "invalid configuration to regenerate"
		tput sgr0
		return 1
	elif ! [ -f "$1" ]
	then
		touch "$1"
	fi

	local line=
	local config=
	local value=
	local target_config="$(grep '^[^# ]' "$1")"

	generate_configuration "$1"

	while read -r line
	do
		config="${line%%=*}" # read configuration name
		value="${line#*=}" # read configuration value
		value="${value%%#*}" # ignore inline comments

		# backward compatibility section
		# if configs name are changed, map their values into new ones
		case "$config" in
			GENERATES_ERROR) config="GENERATES_RUNTIME_ERROR" ;;
			LANGUAGE) config="SYNTAX" ;;
			CHAPTER_TEMPLATE)
				if [ "$validation_check" == "202012271813" ] && [ "$(grep "toc" <<< "$value")" == "" ]
				then
					value="${value%\"} toc\""
				fi ;;
		esac

		sed -i "/^#${config}=/s/^#\(${config}\)=.*/\1=${value}/" "$1"
	done <<< "$target_config"
}

# requires path to page
function validate_page {
	local page=
	local extension=

	for extension in alias.txt title.txt comment.txt reference.txt config
	do
		page="${1%.*}.${extension}"

		if ! [ -f "$page" ]
		then
			if [ "$extension" = "config" ]
			then
				generate_configuration "$1"
			else
				touch "$page"
			fi
		else
			if [ "$extension" = "config" ]
			then
				regenerate_configuration "$page"
			fi
		fi
	done
}

# requires path to chapter
function validate_chapter {
	local page=
	local extension=

	if ! [ -f "${1%/}/.index" ]
	then
		echo "README.md" > "${1%/}/.index"
	elif [ "$(head -n1 "${1%/}/.index")" != "README.md" ]
	then
		sed -i -e '/README.md/d' -e '1i README.md' "${1%/}/.index"
	fi

	# update configuration of chapter
	regenerate_configuration "${1%/}/.config"

	for extension in md config alias.txt title.txt comment.txt reference.txt
	do
		page="${1%/}/README.${extension}"

		if [ "$extension" = "config" ]
		then
			# configuration for readme file
			echo "EXECUTABLE=false" > "$page"
			echo "SOURCE=false" >> "$page"
			echo "INPUT=false" >> "$page"
			echo "OUTPUT=false" >> "$page"
			# update configuration of readme
			regenerate_configuration "$page"
		elif ! [ -f "$page" ]
		then
			if [ "$extension" = "md" ]
			then
				echo -e "# Milestone Notebooks\n" > "$page"
				echo -n "This file is automatically created by " >> "$page"
				echo -n "<b>Practice Manager</b> " >> "$page"
				echo -n "and is part of the " >> "$page"
			   	echo -n "<a href=\"https://github.com/briansalehi/milestone.git\">" >> "$page"
				echo -n "<b>Milestone</b></a> project." >> "$page"
			else
				touch "$page"
			fi
		fi
	done
}

# requires relative path to list
function validate_configuration {
	local directory="${1%/*}"
	local members
	local line
	local file

	if ! [ -f "$1" ]
	then
		tput setaf $SEVERITY_HIGH
		echo "unindexed directory: $directory/" >&2
		tput sgr0
		return 1
	fi

	while read -r line
	do
		line="${line%% *}"
		if [ -f "$directory/$line" ]
		then
			validate_page "$directory/$line"
		elif [ -d "$directory/$line" ]
		then
			validate_chapter "$directory/$line"
			if ! validate_configuration "$directory/$line/.index"
			then
				return 1
			fi
		else
			tput setaf $SEVERITY_HIGH
			echo "missing entry: $directory/$line" >&2
			tput sgr0
		fi
	done < "$1"
}

# requires absolute path to source to configure corresponding variables
function update_configuration {
	local directory
	local config

	for level in ${1//\//$'\n'}
	do
		if [ -d "$directory$level" ]
		then
			directory="$directory$level/"
		elif [ -f "$directory$level" ]
		then
			directory="$directory${level%.*}"
		fi

		config="$directory.config"

		if [ -f "$config" ]
		then
			source "$config"
		fi
	done
}

# requires scheme
# requires page name
function create_command_scheme {
	local scheme="$1"
	local page="$2"
	local headers="$3"
	local component
	command_scheme=

	for component in $scheme
	do
		case "$component" in
			compiler) command_scheme+="$COMPILER " ;;
			compiler_options) command_scheme+="$COMPILER_OPTIONS " ;;
			linker) command_scheme+="$LINKER " ;;
			linker_options) command_scheme+="$LINKER_OPTIONS " ;;
			running_options) command_scheme+="$RUNNING_OPTIONS " ;;
			object) command_scheme+="${source%.*}.${OUTPUT_OBJECT:-o} " ;;
			source) command_scheme+="${source} " ;;
			binary) command_scheme+="${source%.*}.bin " ;;
			headers) command_scheme+="$headers " ;;
			page|pagename|rawname) command_scheme+="${source%.*} " ;;
			location) command_scheme+="${source%/*} " ;;
			makefile) local makefile="${source%.*}.make"; command_scheme+="${makefile##*/} " ;;
			extension-*) command_scheme+="${source%.*}.${component#extenion-} " ;;
			*) command_scheme+="$component " ;;
		esac
	done
	command_scheme="${command_scheme//  / }"
	command_scheme="${command_scheme% }"
}

# requires path to page
# requires compile/link/run option
# requires command
# optional syntax
function generate_execution_mode {
	local page="${1}"
	local mode="${2:-compile}"
	local command="${3}"
	local syntax="${4:-practices}"

	if [ -z "$command" ]
	then
		tput setaf $SEVERITY_HIGH
		echo "execution command not specified for ${mode}: $page"
		tput sgr0
		return 1
	fi

	generate_html_header 4 "${mode}"
	generate_html_code begin command-line language-bash #"data-user=\"${syntax}\" data-host=\"milestone\""
	echo "$command" >> "./html-files/${index}.html"
	generate_html_code end
}

# requires absolute path to source
# option headers and required files
function compile_source {
	local source="$1"
	local page="${1%.*}"
	page="${page##*/}"
	local location="${1%/*}"

	if [ "${EXECUTABLE:-false}" != "true" ]
	then
		return 1
	fi

	local syntax=
	if [ -n "$SYNTAX" ]
	then
		syntax="$SYNTAX"
	else
		syntax="${1##*.}"
	fi

	generate_html_breaker
	generate_html_header 3 "Execution"

	local binary="${1%.*}.bin"
	OUTPUT_OBJECT="${OUTPUT_OBJECT:-o}"
	local object="${1%.*}.${OUTPUT_OBJECT#.}"
	local headers="$@"
	headers="${headers/$1 }"
	local includes=
	local output="${1%.*}.output.txt"
	local compilation_error="${1%.*}.compilation.error.txt"
	local linkage_error="${1%.*}.linkage.error.txt"
	local output_change_time
	local source_change_time
	local component=

	if [ "${COMPILABLE:-false}" = "true" ] && [ -z "$COMPILER" ]
	then
		tput setaf $SEVERITY_HIGH
		echo "compiler not specified for: $1" >&2
		tput sgr0
		return 1
	fi

	if [ "${INCLUDES:-false}" != "true" ]
	then
		headers=
	fi

	if [ "${CAPTURE_SCREENSHOT:-false}" == "true" ]
	then
		output="${1%.*}.screenshot.png"
	else
		output="${1%.*}.output.txt"
	fi

	source_change_time=$(stat -c "%Y" "$1")

	if [ -f "$output" ]
	then
		output_change_time=$(stat -c "%Y" "$output")
	else
		output_change_time=0
	fi

	# build compilation scheme
	create_command_scheme "${COMPILATION_SCHEME/options/compiler_options}" "$source" "$headers"
	local compilation_command="$command_scheme"

	# build post compilation scheme
	create_command_scheme "${POST_COMPILATION_SCHEME/optionos/compiler_options}" "$source" "$headers"
	local post_compilation_command="$command_scheme"

	if ! [ -f "$output" ] || [ "$source_change_time" -gt "$output_change_time" ]
	then
		if [ "${COMPILABLE:-false}" = "true" ]
		then
			if ! $compilation_command &> "$compilation_error"
			then
				if [ "${GENERATES_COMPILATION_ERROR:-false}" != "true" ]
				then
					tput setaf $SEVERITY_HIGH
					echo "compilation error: $1" >&2
					echo "  command: $compilation_command" >&2
					tput sgr0
					return 1
				fi
			fi

			if [ -n "$post_compilation_command" ] && ! $post_compilation_command &>> "$compilation_error"
			then
				if [ "${GENERATES_COMPILATION_ERROR:-false}" != "true" ]
				then
					tput setaf $SEVERITY_HIGH
					echo "post compilation error: $1" >&2
					echo "  command: $post_compilation_command" >&2
					tput sgr0
					return 1
				fi
			fi

			if [ "${GENERATES_COMPILATION_ERROR:-false}" != "true" ] || [ "$(wc -w < "$compilation_error")" -eq 0 ]
			then
				rm "$compilation_error"
			fi
		elif [ "${LINKABLE:-false}" = "true" ]
		then
			if [ -f "$binary" ]
			then
				unlink "$binary"
			fi
			ln -s "$PWD/${1/\.\//}" "${binary}"
		fi
	fi

	if [ "${COMPILABLE:-false}" = "true" ]
	then
		compilation_command="${compilation_command//$location\//}"
		generate_execution_mode "$1" compile "$compilation_command" "$syntax"
	fi

	# build linkage scheme
	create_command_scheme "${LINKAGE_SCHEME/options/linker_options}" "$source" "$headers"
	local linkage_command="$command_scheme"

	if [ "${LINKABLE:-false}" = "true" ] && ! [ -f "$output" ]\
	   	|| [ "$source_change_time" -gt "$output_change_time" ]
	then
		if [ "${LINKABLE:-false}" = "true" ] && [ -n "$LINKER" ]
		then
			if ! $linkage_command 2> "$linkage_error"
			then
				if [ "${GENERATES_LINKAGE_ERROR:-false}" != "true" ]
				then
					tput setaf $SEVERITY_HIGH
					echo "linkage error for: $1" >&2
					echo "  command: $linkage_command" >&2
					tput sgr0
					return 1
				fi
			fi

			if [ "${GENERATES_LINKAGE_ERROR:-false}" != "true" ] || [ "$(wc -w < "$linkage_error")" -eq 0 ]
			then
				rm "$linkage_error"
			fi
		elif [ "${LINKABLE:-false}" = "true" ] && [ -z "$LINKER" ]
		then
			tput setaf $SEVERITY_HIGH
			echo "linker not specified for: $1" >&2
			tput sgr0
			return 1
		fi
	fi

	if [ "${LINKABLE:-false}" = "true" ]
	then
		linkage_command="${linkage_command//$location\//}"
		generate_execution_mode "$1" link "$linkage_command" "$syntax"
	fi
}

# requires path to page
# optional floor to start indexing directories
# sets page_index and page_hierarchy variables
function index_page {
	local floor="${2:-1}"

	local depth=1
	local entry=
	local hierarchy=
	local index=
	page_index=
	page_hierarchy=

	for entry in ${1//\//$'\n'}
	do
		hierarchy="${hierarchy:-$entry}"

		if [ "$depth" -gt "$floor" ]
		then
			match="$(grep -n "^$entry" "${hierarchy}/.index")"
			match="${match%%:*}"
			match="${match%% *}"

			if [ "${match:-0}" -gt 0 ]
			then
				((match--)) # shift index down because of readme indexes
			fi
			index+="${match:-0}."
		fi

		((depth++))
		hierarchy="${hierarchy}/${entry}"
	done
	page_index="${index%.}"
	page_hierarchy="${hierarchy#\.\/}"
}

# requires path to page
# optional up/down for direction of growth
# sets deepest_page variable
function deepest_path {
	local hierarchy="${1%/}"
	local direction="${2:-up}"

	local entry=
	local tool=
	deepest_page=

	if [ "$direction" = "up" ]
	then
		tool="head"
	elif [ "$direction" = "down" ]
	then
		tool="tail"
	else
		return 1
	fi

	while true
	do
		if [ -d "$hierarchy" ] && [ -f "${hierarchy}/.index" ]
		then
			entry="$("$tool" -n1 "${hierarchy}/.index")"
			entry="${entry%% *}"
			if [ -n "$entry" ]
			then
				hierarchy="${hierarchy}/${entry}"
			else
				break
			fi
		else
			break
		fi
	done
	deepest_page="$hierarchy"
}

# requires path to page
# optional up/down for direction of growth
# sets page_index and page_hierarchy variables
# note: empty variables means there is no neighbor
function nearest_path {
	local hierarchy="${1%/}"
	local page="${hierarchy##*/}"
	hierarchy="${hierarchy%/*}"
	local direction="${2:-up}"
	local match=
	local option=
	local first="true"

	if [ "$direction" = "up" ]
	then
		option="-B1"
	elif [ "$direction" = "down" ]
	then
		option="-A1"
	else
		return 1
	fi

	while [ "$hierarchy" != "." ] || [ "$first" = "true" ]
	do
		if [ "$hierarchy" = "." ]
		then
			first="false"
		fi

		match="$(grep "$option" "^$page" "${hierarchy}/.index")"

		if [ "$direction" = "up" ]
		then
			match="${match%$'\n'*}"
		else
			match="${match#*$'\n'}"
		fi
		match="${match%% *}"

		if [ "$match" = "$page" ]
		then
			page="${hierarchy##*/}"
			hierarchy="${hierarchy%/*}"
		else
			if [ "$direction" = "up" ]
			then
				direction="down"
			else
				direction="up"
			fi

			if [ -d "${hierarchy}/${match}" ]
			then
				deepest_path "${hierarchy}/${match}" "$direction"
				page="$deepest_page"
			else
				page="${hierarchy}/${match}"
			fi

			index_page "$page"
			break
		fi
	done
}

# zero-out badge variable before use
# requires path to chapter
function generate_group_badge {
	local entry=
	while read -r entry
	do
		if [ "$entry" = "README.md" ]
		then
			continue
		elif [ -d "${1%/*}/${entry%% *}" ]
		then
			generate_group_badge "${1%/*}/${entry}/.index"
		elif [ -f "${1%/*}/${entry%% *}" ]
		then
			((badge++))
		fi
	done < "$1"
}

# requies process id to kill
# requies seconds to wait before strike
function process_kill {
	sleep "$2"
	kill -SIGTERM "$1"
}

# requires source file
function capture_screenshot {
	local source="$1"
	local imagefile="${source%.*}.screenshot.png"

	local binary="${source%.*}"
	binary="${binary##*/}"

	if [ -f "${source%.*}.bin" ] && ${source%.*}.bin &>/dev/null &
	then
		local lifetime=0
		local pid=

		while ! pid=$(pgrep "$binary"); do
			if [ "$lifetime" -gt 50 ]
			then
				tput setaf $SEVERITY_HIGH
				echo "screenshot session timed out: $source"
				tput sgr0
				return 1
			fi
			sleep .1
			((lifetime++))
		done

		if gnome-screenshot --display :0 --file "$imagefile" --delay 1 --window &>/dev/null
		then
			if kill "$pid" &>/dev/null
			then
				tput setaf $SEVERITY_LOW
				echo "screenshot captured: ${imagefile}"
				tput sgr0
			else
				tput setaf $SEVERITY_HIGH
				echo "failed to kill process after screenshot: $source"
				tput sgr0
				rm -f "${source%.*}.screenshot.png"
			fi
		else
			tput setaf $SEVERITY_HIGH
			echo "screenshot tool (gnome-screenshot) failed to run: $source"
			tput sgr0
			rm -f "${source%.*}.screenshot.png"
		fi
	else
		tput setaf $SEVERITY_HIGH
		echo "failed to run program for screenshot: $source"
		tput sgr0
		rm -f "${source%.*}.screenshot.png"
	fi
}

# requires path to page
function run_program {
	local source="$1"
	OUTPUT_OBJECT="${OUTPUT_OBJECT:-o}"
	local object="${1%.*}.${OUTPUT_OBJECT#.}"
	local headers="$@"
	headers="${headers/$1 }"
	local output=

	local location="${1%/*}"
	local component=
	local source_change_time=
	local output_change_time=

	source_change_time=$(stat -c "%Y" "$1")

	if [ "${CAPTURE_SCREENSHOT:-false}" == "true" ]
	then
		output="${1%.*}.screenshot.png"
	else
		output="${1%.*}.output.txt"
	fi

	local runtime_error="${1%.*}.runtime.error.txt"
	if [ -f "$output" ]
	then
		output_change_time=$(stat -c "%Y" "$output")
	else
		output_change_time=0
	fi

	# build running scheme
	create_command_scheme "${RUNNING_SCHEME/options/running_options}" "$source" "$headers"
	local running_command="$command_scheme"

	if [ "${RUNNABLE:-false}" = "true" ]
	then
		if [ "${OUTPUT:-false}" = "true" ] && [ "$source_change_time" -gt "$output_change_time" ]
		then
			if [ "${CAPTURE_SCREENSHOT:-false}" == "true" ]
			then
				capture_screenshot "$source" 2>/dev/null
			elif [ -f "$input" ]
			then
				if ! $running_command < "$input" 2> "$runtime_error" 1> "$output"
				then
					if [ "${GENERATES_RUNTIME_ERROR:-false}" != "true" ]
					then
						tput setaf $SEVERITY_HIGH
						echo "running program failed: $source" >&2
						echo "  command: $running_command" >&2
						tput sgr0
					fi
				fi
				# remove empty or unwanted error files
				if [ "${GENERATES_RUNTIME_ERROR:-false}" != "true" ] || [ "$(wc -w < "$runtime_error")" -eq 0 ]
				then
					rm "$runtime_error"
				fi
			else
				if ! $running_command 2> "$runtime_error" 1> "$output"
				then
					if [ "${GENERATES_RUNTIME_ERROR:-false}" != "true" ]
					then
						tput setaf $SEVERITY_HIGH
						echo "running program failed: $source" >&2
						echo "  command: $running_command" >&2
						tput sgr0
					fi
				fi
				# remove empty or unwanted error files
				if [ "${GENERATES_RUNTIME_ERROR:-false}" != "true" ] || [ "$(wc -w < "$runtime_error")" -eq 0 ]
				then
					rm "$runtime_error"
				fi
			fi
		fi

		running_command="${running_command//$location\//./}"
		generate_execution_mode "$1" run "$running_command" "$SYNTAX"
	fi
}

# functions to generate html pages
###############################################################################

# requires path to page
function generate_reference_section {
	local reference="${1%.*}.reference.txt"

	if ! [ -f "$reference" ] || [ "$(wc -w < "$reference")" -eq 0 ]
	then
		tput setaf "$SEVERITY_MEDIUM"
		echo "reference not specified: $1" >&2
		tput sgr0
		return 1
	fi

	generate_html_breaker
	generate_html_header 3 "References"
	generate_html_list begin list-group

	local line
	while read -r line
	do
		generate_html_item "$line" list-group-item
	done < "$reference"

	generate_html_list end
}

# requires path to page
function generate_navigation_section {
	local hierarchy=
	local entry=
	local page=
	local title=
	local local_index=
	local depth=1

	generate_html_ordered_list "$1" begin breadcrumb
	generate_html_item_with_link "Home" "/" breadcrumb-item "$depth"
	((depth++))

	for entry in ${1//\//$'\n'}
	do
		if [ -z "$hierarchy" ]
		then
			hierarchy="$entry"
			continue
		fi

		hierarchy="${hierarchy}/${entry}"

		if [ -d "$hierarchy" ] && [ -f "${hierarchy}/README.title.txt" ]
		then
			if [ "${hierarchy}/README.md" != "$1" ]
			then
				title="$(cat "${hierarchy}/README.title.txt")"
				local_index="$hierarchy"
				local_index="${local_index//[^\/]/}"
				local_index="${#local_index}"
				page="$(cut -d"." -f1-"$local_index" <<< "$page_index").0.html"
				generate_html_item_with_link "${title:-"..."}" "$page" breadcrumb-item "$depth"
				((depth++))
			fi
		elif [ -f "$hierarchy" ] && [ -f "${hierarchy%.*}.title.txt" ]
		then
			title="$(cat "${hierarchy%.*}.title.txt")"
			generate_html_item "${title:-"..."}" "breadcrumb-item active"
		else
			tput setaf $SEVERITY_HIGH
			echo "untitled breadcrumb: ${hierarchy}"
			tput sgr0
			generate_html_item "..." breadcrumb-item
		fi
	done

	generate_html_ordered_list "$1" end
}

function generate_index_section {
	local tag="<h1>"

	echo -n "  ${tag}${index%.0}. " >> "./html-files/${index}.html"
}

# requires path to page
function generate_header_section {
	local page="${1%.*}"
	local header="$page.title.txt"
	page="${page##*/}"
	local title

	if ! [ -f "$header" ]
	then
		tput setaf $SEVERITY_MEDIUM
		echo "header not found: $header" >&2
		tput sgr0
	elif [ -z "$(cat "$header")" ]
	then
		tput setaf $SEVERITY_MEDIUM
		echo "empty header: $header" >&2
		tput sgr0
	else
		title="$(cat "$header")"
		generate_html_header 2 "$title"
	fi
}

# requires path to page
function generate_page_name {
	local tag="<cite>"
	local tag_end="</cite>"

	echo "  ${tag}${1##*/}${tag_end}" >> "./html-files/${index}.html"
}

# requires path to page
function generate_source_section {
	if [ "${SOURCE:-false}" != "true" ]
	then
		return 1
	fi

	generate_html_breaker
	generate_html_header 3 "Source"
	while [ $# -gt 0 ]
	do
		generate_page_name "${1}"

		local syntax=
		if [ -n "$SYNTAX" ]
		then
			syntax="$SYNTAX"
		else
			syntax="${1##*.}"
		fi

		generate_html_code begin line-numbers "language-${syntax}"
		OLD_IFS="$IFS"
		IFS=
		local line
		while read -r line
		do
			line="${line//&/&amp;}"
			line="${line//\"/&quot;}"
			line="${line//\'/&apos;}"
			line="${line//</&lt;}"
			line="${line//>/&gt;}"
			echo "    $line" >> "./html-files/${index}.html"
		done < "$1"
		IFS="$OLD_IFS"
		generate_html_code end
		shift
	done
}

# requires absolute path to page
function generate_output_section {
	local page="${1%.*}"
	local binary="$page.bin"
	local output="${page}.output.txt"
	local compilation_error="$page.compilation.error.txt"
	local linkage_error="$page.linkage.error.txt"
	local runtime_error="$page.runtime.error.txt"
	local input="$page.input.txt"
	page="${page##*/}"
	local line

	if ! compile_source $@
	then
		return 1
	fi

	if ! run_program "$1" $@
	then
		return 1
	fi

	if [ "${INPUT:-false}" = "true" ] && [ -f "$input" ]
	then
		generate_html_breaker
		generate_html_header 3 Input
		generate_html_code begin language-bash

		while read -r line
		do
			echo "$line" >> "./html-files/${index}.html"
		done < "$input"

		generate_html_code end
	fi

	if [ "${OUTPUT:-false}" = "true" ]
	then
		if [ "${CAPTURE_SCREENSHOT:-false}" == "true" ]
		then
			generate_html_breaker
			generate_html_header 3 Output
			generate_page_name "${1%.*}.png"
			find_index_alias "$page_index"
			generate_html_screenshot "$1"
		elif [ -f "$output" ]
		then
			if [ "$(wc -w < "$output")" -gt 0 ]
			then
				generate_html_breaker
				generate_html_header 3 Output
				generate_html_code begin language-txt

				while read -r line
				do
					echo "$line" >> "./html-files/${index}.html"
				done < "$output"

				if [ "$(wc -l < "$output")" -eq 0 ]
				then
					echo >> "$output"
				fi

				generate_html_code end
			fi
		else
			tput setaf $SEVERITY_HIGH
			echo "output file not found: $output" >&2
			tput sgr0
		fi
	fi

	local generates_error="false"
	if [ "${GENERATES_COMPILATION_ERROR:-false}" = "true" ] || \
		[ "${GENERATES_LINKAGE_ERROR:-false}" = "true" ] || \
		[ "${GENERATES_RUNTIME_ERROR:-false}" = "true" ]
	then
		if [ -f "$compilation_error" ] || [ -f "$linkage_error" ] || [ -f "$runtime_error" ]
		then
			generate_html_breaker
			generate_html_header 3 Output
		fi
	fi

	if [ "${ERROR:-false}" = "true" ] && [ "${GENERATES_COMPILATION_ERROR:-false}" = "true" ]
	then
		if [ -f "$compilation_error" ]
		then
			if [ "$(wc -w < "$compilation_error")" -gt 0 ]
			then
				generate_html_breaker
				generate_html_header 3 Error
				generate_html_code begin language-bash

				while read -r line
				do
					echo "$line" >> "./html-files/${index}.html"
				done < "$compilation_error"

				if [ "$(wc -l < "$compilation_error")" -eq 0 ]
				then
					echo >> "$compilation_error"
				fi

				generate_html_code end
			fi
		else
			tput setaf $SEVERITY_HIGH
			echo "compilation error file wanted but not found: $compilation_error" >&2
			tput sgr0
		fi
	fi

	if [ "${ERROR:-false}" = "true" ] && [ "${GENERATES_LINKAGE_ERROR:-false}" = "true" ]
	then
		if [ -f "$linkage_error" ]
		then
			if [ "$(wc -w < "$linkage_error")" -gt 0 ]
			then
				generate_html_breaker
				generate_html_header 3 Error
				generate_html_code begin language-bash

				while read -r line
				do
					echo "$line" >> "./html-files/${index}.html"
				done < "$linkage_error"

				if [ "$(wc -l < "$linkage_error")" -eq 0 ]
				then
					echo >> "$linkage_error"
				fi

				generate_html_code end
			fi
		else
			tput setaf $SEVERITY_HIGH
			echo "linkage error file wanted but not found: $linkage_error" >&2
			tput sgr0
		fi
	fi

	if [ "${ERROR:-false}" = "true" ] && [ "${GENERATES_RUNTIME_ERROR:-false}" = "true" ]
	then
		if [ -f "$runtime_error" ]
		then
			if [ "$(wc -w < "$runtime_error")" -gt 0 ]
			then
				generate_html_breaker
				generate_html_header 3 Error
				generate_html_code begin language-bash

				while read -r line
				do
					echo "$line" >> "./html-files/${index}.html"
				done < "$runtime_error"

				if [ "$(wc -l < "$runtime_error")" -eq 0 ]
				then
					echo >> "$runtime_error"
				fi

				generate_html_code end
			fi
		else
			tput setaf $SEVERITY_HIGH
			echo "runtime error file wanted but not found: $runtime error" >&2
			tput sgr0
		fi
	fi
}

# requires absolute path to page
function generate_comment_section {
	if [ "$COMMENT" != "true" ]
	then
		return 1
	fi

	local page="${1%.*}"
	local comment="$page.comment.txt"
	page="${page##*/}"

	if ! [ -f "$comment" ]
	then
		tput setaf $SEVERITY_MEDIUM
		echo "comment not found: $comment" >&2
		tput sgr0
	elif [ -z "$(cat "$comment")" ]
	then
		tput setaf $SEVERITY_MEDIUM
		echo "empty comment: $comment" >&2
		tput sgr0
	else
		generate_html_div "$1" begin comment-style
		OLD_IFS="$IFS"
		while read -r line
		do
			echo "$line" | sed -e 's/\([\.!?;:]\)$/\1<br \/>/' -e 's/^$/<br \/>/' >> "./html-files/${index}.html"
		done < "$comment"
		IFS="$OLD_IFS"

		for match in $(grep -n "^\!\[.*\]$" "./html-files/${index}.html")
		do
			local linenumber="${match%%:*}"
			local image="${match#*[}"
			image="${image%]*}"

			find_index_alias "$page_index"
			generate_html_image "$1" "$image" "$linenumber"
			sed -i "${linenumber}d" "./html-files/${index}.html"
		done
		generate_html_div "$1" end
	fi
}

# requires index
function find_index_alias {
	page_alias=

	if [ "$1" = "0" ]
	then
		return 0
	fi
	
	local alias_file=
	local alias=
	local location=
	local sourcefile=
	local entry=
	for entry in ${1//./ }
	do
		((entry++))
		if [ "$entry" = "0" ]
		then
			tput setaf $SEVERITY_HIGH
			echo "invalid index number: $1 => $location"
			tput sgr0
			return 1
		fi

		if [ -z "$location" ]
		then
			sourcefile="$(sed -n "${entry}p" ".index")"
			location="${sourcefile%% *}"
		else
			sourcefile="$(sed -n "${entry}p" "${location}/.index")"
			location="${location}/${sourcefile%% *}"
		fi

		if [ -d "$location" ]
		then
			alias_file="${location}/README.alias.txt"
		elif [ -f "$location" ]
		then
			if [ "$entry" = "1" ]
			then
				continue
			fi
			alias_file="${location%.*}.alias.txt"
		else
			tput setaf $SEVERITY_HIGH
			echo "invalid index for aliasing: ${1} => ${location}"
			tput sgr0
			return 1
		fi

		if [ -f "$alias_file" ] && [ "$(wc -m < "$alias_file")" -gt 0 ]
		then
			alias="${alias}/$(cat "$alias_file")"

			if [ "$entry" = "0" ]
			then
				alias="${alias}/index"
			fi
		else
			return 1
		fi
	done

	page_alias="$alias"
}

# requires absolute path to page
function generate_quick_access_section {
	local page="${1%.*}"
	page="${page##*/}"
	local current_index=
	local next_index=
	local previous_index=
	local button=

	index_page "$1"
	current_index="$page_index"

	nearest_path "$1" up
	if [ "$page_index" = "$current_index" ]
	then
		previous_index=
	else
		previous_index="$page_index"
	fi

	nearest_path "$1" down
	if [ "$page_index" = "$previous_index" ]
	then
		next_index=
	else
		next_index="$page_index"
	fi

	generate_html_list begin pager

	find_index_alias "${previous_index:-0}"

	button="previous page"
	if [ -n "$previous_index" ]
	then
		previous_index="${previous_index}.html"
		generate_html_item_with_link "$button" "${page_alias:-$previous_index}" previous "B"
	else
		generate_html_item_with_link "$button" "#" "previous disabled"
	fi

	button="top page"
	if [ -z "$previous_index" ] || [ -z "$next_page" ]
	then
		generate_html_item_with_link "$button" "/" top "T"
	fi

	find_index_alias "${next_index:-0}"

	button="next page"
	if [ -n "$next_index" ]
	then
		next_index="${next_index}.html"
		generate_html_item_with_link "$button" "${page_alias:-$next_index}" next "F"
	else
		generate_html_item_with_link "$button" "#" "next disabled"
	fi

	generate_html_list end
}

function generate_table_of_content {
	local hierarchy="${1%/*}"
	local heading="${2:-false}"
	local nest="${3:-1}"
	local entry=
	local indentation=
	local local_index=
	local title=
	local page_link=

	while read -r entry
	do
		entry="${entry%% *}"
		if [ -d "${hierarchy}/${entry}" ] || [ "$entry" = "README.md" ]
		then
			if [ "$entry" = "README.md" ]
			then
				index_page "${hierarchy}/${entry}"
				if [ "$page_index" = "0" ] || [ "$heading" == "true" ]
				then
					heading="false"
					#title="$(cat "${hierarchy}/${entry%.*}.title.txt")"
					#generate_html_header_with_link "$1" 3 "$title" "${page_index}.html"
					generate_html_breaker
					generate_html_header 3 "Table of Content"
					generate_list_group_root "$1" begin
				else
					badge=0
					generate_group_badge "$1"
					page_number="${page_index%.0}"
					page_number="${page_number##*.}"
					title="${page_number:-0}. $(cat "${hierarchy}/${entry%.*}.title.txt")"
					if [ "$nest" -gt 0 ]
					then
						generate_list_group_collapse_item "${page_index//./-}" "$title" "$badge"
					else
						page_link="${page_index}.html"
						find_index_alias "$page_index"
						generate_list_group_item "${page_alias:-$page_link}" "$title" "$nest" "$badge"
					fi
					generate_list_group "$1" begin "${page_index//./-}"
				fi
			elif [ -f "${hierarchy}/${entry%/}/.index" ]
			then
				if [ "$nest" -gt 0 ]
				then
					generate_table_of_content "${hierarchy}/${entry%/}/.index" "false" "$[nest - 1]"
					generate_list_group "$1" end
				fi
			else
				tput setaf $SEVERITY_HIGH
				echo "broken hierarchy in ${hierarchy}/${entry%/}/.index"
				tput sgr0
			fi
		elif ! [ -f "${hierarchy}/${entry}" ]
		then
			tput setaf $SEVERITY_HIGH
			echo "missing entry in table of content: ${hierarchy}/${entry}"
			tput sgr0
			return 1
		elif ! [ -f "${hierarchy}/${entry%.*}.title.txt" ]
		then
			tput setaf $SEVERITY_HIGH
			echo "missing entry title in table of content: ${hierarchy}/{$entry}"
			tput sgr0
			return 2
		else
			index_page "${hierarchy}/${entry}"
			page_number="${page_index%.0}"
			page_number="${page_number##*.}"
			title="${page_number:-0}. $(cat "${hierarchy}/${entry%.*}.title.txt")"
			page_link="${page_index}.html"
			find_index_alias "$page_index"
			generate_list_group_item "${page_alias:-$page_link}" "$title" "$nest"
		fi
	done < "${hierarchy}/.index"
}

# requires path to page
# requires index
function generate_alias {
	local path="${1%/}"
	local index="$2"

	if [ "$path" = "." ]
	then
		return 0
	fi
	
	local alias_file=
	local alias="html-files"
	local target=
	local location=
	local entry=
	for entry in ${1//\//$'\n'}
	do
		if [ -z "$location" ]
		then
			location="$entry"
			continue
		elif [ "$entry" = "." ]
		then
			location="./$entry"
			continue
		else
			location="${location}/${entry}"
		fi

		if [ -f "${location}" ]
		then
			alias_file="${location%.*}.alias.txt"
		elif [ -d "${location}" ]
		then
			alias_file="${location}/README.alias.txt"
			target="../${target}"
		else
			tput setaf $SEVERITY_HIGH
			echo "aliasing failed due to broken hierarchy: ${location}"
			tput sgr0
			return 1
		fi

		if [ -f "$alias_file" ] && [ "$(wc -m < "$alias_file")" -gt 0 ]
		then
			alias="${alias}/$(cat "$alias_file")"

			if [ -d "$location" ] && ! [ -d "$alias" ]
			then
				if ! mkdir "$alias"
				then
					tput setaf $SEVERITY_HIGH
					echo "cannot create alias directory: $alias"
					tput sgr0
					return 1
				fi
			fi

			if [ -d "$path" ] && [ "$path" == "$location" ]
			then
				alias="${alias}/index"
			fi
		else
			tput setaf $SEVERITY_MEDIUM
			echo "alias not found: ${path}"
			tput sgr0
			return 1
		fi
	done

	target="${target}${index}" # {../../../}{3.1.1.html}

	if ! ln -s "html-files/$index" "$alias"
	then
		tput setaf $SEVERITY_HIGH
		echo "failed to create link for alias: $path"
		echo "  target: $target"
		echo "  alias: $alias"
		tput sgr0
		return 1
	fi
}

function generate_index_page {
	local page="./html-files/index.html"
	index=index

	update_configuration "$page"
	generate_html_section "$page" begin

		generate_html_head begin "$page"
			load_css ajax.html
			load_css bootstrap.html
			load_css prism.html

			generate_html_style begin
			load_css general.css
			load_css darkmode.css
			load_css breadcrumb.css
			load_css list-group.css
			load_css pager.css
			load_css prism-overrides.css
			load_css octicon.css
			generate_html_style end
		generate_html_head end

		generate_html_body begin

			generate_html_header_with_link "$page" 2 "Notebooks" "0.html"
			generate_table_of_content "./.index" "true" "2"
			generate_list_group_root "$page" end

			load_javascript jquery.html
			load_javascript bootstrap.html
			load_javascript prism.html

			load_syntax_highlighting "$page" bash.html

			generate_html_script begin
			load_javascript darkmode.js
			load_javascript list-group.js
			generate_html_script end

		generate_html_body end

	generate_html_section "$page" end
}

# functions to start the script working
###############################################################################

# requires path to page
function generate_page {
	index_page "$1"
	index="$page_index"
	generate_alias "$1" "${index}.html"
	update_configuration "$1"

	generate_html_section "$1" begin

		generate_html_head begin "$1"
			load_css ajax.html
			load_css bootstrap.html
			load_css prism.html

			generate_html_style begin
			load_css general.css
			load_css darkmode.css
			load_css breadcrumb.css
			load_css list-group.css
			load_css pager.css
			load_css prism-overrides.css
			load_css octicon.css
			generate_html_style end
		generate_html_head end

		generate_html_body begin

	local section=
	for section in $PAGE_TEMPLATE
	do
		case "$section" in
			navigation) NAVIGATION=true; generate_navigation_section "$1" ;;
			title) TITLE=true; generate_header_section "$1" ;;
			reference) generate_reference_section "$1" ;;
			comment) COMMENT=true; generate_comment_section "$1" ;;
			source) SOURCE=true; generate_source_section $@ ;;
			execution) EXECUTABLE=true ;;
			output) OUTPUT=true; generate_output_section $@ ;;
			compilation_error) ERROR=true ;;
			linkage_error) ERROR=true ;;
			runtime_error) ERROR=true ;;
			input) INPUT=true ;;
			error) ERROR=true ;;
			pagination) PAGINATION=true; generate_quick_access_section "$1" ;;
			*) tput setaf $SEVERITY_HIGH; echo "invalid section name \`$section\`"; tput sgr0; continue ;;
		esac
	done

			load_javascript jquery.html
			load_javascript bootstrap.html
			load_javascript prism.html

			load_syntax_highlighting "$1"
			if [ "$SYNTAX" != "bash" ]
			then
				load_syntax_highlighting "$1" bash.html
			fi

			generate_html_script begin
			load_javascript darkmode.js
			load_javascript list-group.js
			generate_html_script end

		generate_html_body end
	generate_html_section "$1" end
	tput setaf $SEVERITY_LOW
	echo "page generated: $1"
	tput sgr0
	index=
}

# requires absolute path to page
function generate_chapter {
	index_page "$1"
	index="$page_index"
	generate_alias "${1%README.md}" "${index}.html"
	update_configuration "$1"

	generate_html_section "$1" begin
		generate_html_head begin "$1"
			load_css ajax.html
			load_css bootstrap.html
			load_css prism.html

			generate_html_style begin
			load_css general.css
			load_css darkmode.css
			load_css breadcrumb.css
			load_css list-group.css
			load_css pager.css
			load_css prism-overrides.css
			load_css octicon.css
			generate_html_style end
		generate_html_head end

		generate_html_body begin

	local section=
	for section in $CHAPTER_TEMPLATE
	do
		case "$section" in
			navigation) NAVIGATION=true; generate_navigation_section "$1" ;;
			title) TITLE=true; generate_header_section "$1" ;;
			reference) generate_reference_section "$1" ;;
			comment) COMMENT=true; generate_comment_section "$1" ;;
			source) SOURCE=true ;;
			execution) EXECUTABLE=true ;;
			output) OUTPUT=true ;;
			input) INPUT=true ;;
			error) ERROR=true ;;
			pagination) PAGINATION=true; generate_quick_access_section "$1" ;;
			toc) TABLE_OF_CONTENT=true;
				generate_table_of_content "${1%/*}/.index" "true" "2"
				generate_list_group_root "${1%/*}/.index" end
				;;
			*) tput setaf $SEVERITY_HIGH; echo "invalid section name \`$section\`"; tput sgr0 ;;
		esac
	done

			load_javascript jquery.html
			load_javascript bootstrap.html
			load_javascript prism.html

			load_syntax_highlighting "$1" bash.html

			generate_html_script begin
			load_javascript darkmode.js
			load_javascript list-group.js
			generate_html_script end

		generate_html_body end
	generate_html_section "$1" end
	index=
}

# requires relative path to list
function expand_list {
	local directory
	local members
	local group

	directory="${1%/*}"

	if ! [ -f "$1" ]
	then
		tput setaf $SEVERITY_HIGH
		echo "unindexed directory: $directory/" >&2
		tput sgr0
		return 1
	fi

	local line
	while read -r line
	do
		members="${line//[^\ ]/}"

		if [ "${#members}" -gt 0 ]
		then
			for file in $line
			do
				if [ -f "$directory/$file" ]
				then
					group="$group $directory/$file"
				else
					tput setaf $SEVERITY_HIGH
					echo "missing group member: $directory/$file" >&2
					tput sgr0
					continue 2
				fi
			done
			generate_page $group
		elif [ -f "$directory/$line" ] && [ "$line" != "README.md" ]
		then
			generate_page "$directory/$line"
		elif [ -f "$directory/$line" ] && [ "$line" = "README.md" ]
		then
			generate_chapter "$directory/$line"
		elif [ -d "$directory/$line" ]
		then
			expand_list "$directory/$line/.index"
		else
			tput setaf $SEVERITY_HIGH
			echo "missing entry: $directory/$line" >&2
			tput sgr0
		fi
		group=
	done < "$1"
}

# requires full path to first index file to recusrively build document
# must be called with trailing ./ in first argument
function generate_manuals {
	if ! [ -f "$1" ]
	then
		tput setaf $SEVERITY_HIGH
		echo "not a practice directory" >&2
		tput sgr0
		return 1
	fi

	if [ -d ./html-files/ ]
	then
		rm -r ./html-files/
	fi

	mkdir ./html-files/

	if expand_list "$1"
	then
		generate_index_page
	fi

	if [ -d icons ]
	then
		cp -r icons html-files/
	fi
}

# functions for specific options
###############################################################################

# requires path to location where practice will be added
function add_page {
	local location="${1%/*}"
	local practice_name="${1##*/}"

	if [ -z "$location" ]
	then
		tput setaf $SEVERITY_HIGH
		echo "location not given" >&2
		tput sgr0
		return 1
	elif [ -z "$practice_name" ]
	then
		tput setaf $SEVERITY_HIGH
		echo "practice name not given" >&2
		tput sgr0
		return 1
	elif ! [ -d "$location" ]
	then
		tput setaf $SEVERITY_HIGH
		echo "location must be a directory: $location" >&2
		tput sgr0
		return 1
	elif [ $(grep -c "^$practice_name$" "${location}/.index") -gt 0 ]
	then
		tput setaf $SEVERITY_HIGH
		echo "duplicate practice name: $practice_name" >&2
		tput sgr0
	fi

	# index practice in corresponding location
	echo "$practice_name" >> "${location}/.index"

	# create practice file itself
	touch "${location}/${practice_name}"
	# create additional files within source
	validate_page "${location}/${practice_name}"
	echo "practice created: ${location}/${practice_name}"
}

# requires path to location where chapter will be added
function add_chapter {
	local location="${1%/*}"
	local chapter_name="${1##*/}"

	if [ -z "$location" ]
	then
		tput setaf $SEVERITY_HIGH
		echo "location not given" >&2
		tput sgr0
		return 1
	elif [ -z "$chapter_name" ]
	then
		tput setaf $SEVERITY_HIGH
		echo "practice name not given" >&2
		tput sgr0
		return 1
	elif ! [ -d "$location" ]
	then
		tput setaf $SEVERITY_HIGH
		echo "location must be a directory: $location" >&2
		tput sgr0
		return 1
	fi

	# if the holding directory itself does not have .index create one!
	if ! [ -f "${location}/.index" ] || [ "$(wc -l < "${location}/.index")" -eq 0 ]
	then
		generate_configuration "${location}"
		extract_configuration "${location}"
		echo "README.md" > "${location}/.index"
		validate_chapter "${location}"
	fi
	echo "$chapter_name" >> "${location}/.index"

	mkdir "${location}/${chapter_name}"
	validate_chapter "${location}/${chapter_name}"
	echo "chapter created: ${location}/${chapter_name}"
}

# requires relative path to practice location
function join_page {
	# index page
	echo "${1##*/}" >> "${1%/*}/.index"
	validate_page "$1"
	echo "practice joined: $1"
}

function join_chapter {
	# index chapter
	echo "${1##*/}" >> "${1%/*}/.index"
	validate_chapter "$1"
	echo "chapter joined: $1"
}

# requires path to page
function remove_page {
	local page="${1##*/}"
	local location="${1%/}"
	location="${location%/*}"

	if [ -f "${location}/.index" ]
	then
		sed -i "/^${page}.*$/d" "${location}/.index"
		echo "practice unlinked"
		echo "you can rejoin this practice again by running \`${0##*/} $1\`"
	else
		tput setaf $SEVERITY_HIGH
		echo "practice page does not exist: ${1/$PWD\//}" >&2
		tput sgr0
		return 1
	fi
}

# requires path to directory
function remove_chapter {
	local location="${1%/}"
	location="${location%/*}"
	local chapter="${1%/}"
	chapter="${chapter##*/}"

	if [ -d "$1" ]
	then
		if [ -f "${location}/.index" ]
		then
			sed -i "/^${chapter}$/d" "${location}/.index"
			echo "chapter unlinked"
			echo "you can rejoin this chapter later by running \`${0##*/} $1\`"
		fi
	else
		tput setaf $SEVERITY_HIGH
		echo "chapter does not exist: ${1/$PWD\//}" >&2
		tput sgr0
		return 1
	fi
}

function rename_page {
	local source="${1%.*}"
	source="${source##*/}"
	local location="${1%/*}"
	local destination="${2%.*}"
	local match=
	local extension=

	if [ "$source" = "$destination" ] && [ "${1##*.}" != "${2##*.}" ]
	then
		mv "$1" "$2"
		echo "changed page extension from:"
		echo "    ${1##*.}"
		echo "to"
		echo "    ${2##*.}"
	else
		for match in $(find "$location" -type f -name "${source}\.*")
		do
			extension="${match##*/}"
			extension="${extension#*.}"
			mv "$match" "${destination}.${extension}"
		done

		echo "renamed page from:"
		echo "    $1"
		echo "to"
		echo "    $2"
	fi

	sed -i "s/^${1##*/}\( \)*/${2##*/}\1/" "${location}/.index"
}

function rename_chapter {
	local source="${1%/}"
	local destination="${2%/}"

	if mv "$source" "$destination"
	then
		sed -i "s/^${source##*/}$/${destination##*/}/" "${source%/*}/.index"
		echo "chapter renamed from:"
		echo "    $1"
		echo "to"
		echo "    $2"
	else
		tput setaf $SEVERITY_HIGH
		echo "failed to rename chapter: $source" >&2
		tput sgr0
		return 1
	fi
}

function move_page {
	local source="$1"
	local destination="$2"

	if [ -f "$destination" ] && [ -f "${source%/*}/.index" ]
	then
		local match=
		source="${1%.*}"
		destination="${2%.*}"

		for match in $(find "${source%/*}" -type f -name "${source##*/}*")
		do
			mv "$match" "${destination%/*}/${destination##*/}${match##*.}"
		done

		sed -i "s/^${1##*/}$/${2##*/}/" "${1%/*}/.index"
		echo "${2##*/}" >> "${2%/*}/.index"
		echo "page moved from:"
		echo "    $1"
		echo "to"
		echo "    $2"
	elif [ -d "$destination" ] && [ -f "${source%/*}/.index" ]
	then
		if mv ${source%.*}.* "$destination"
		then
			sed -i "/^${source##*/}$/d" "${source%/*}/.index"
			join_page "${destination%/}/${source##*/}"
		else
			tput setaf $SEVERITY_HIGH
			echo "failed to move source: $source" >&2
			tput sgr0
		fi
	else
		tput setaf $SEVERITY_HIGH
		echo "page not indexed: $source" >&2
		tput sgr0
	fi
}

function move_chapter {
	local source="${1%/}"
	local destination="${2%/}"
	local local_index=

	if [ -n "$3" ]
	then
		local_index="$3"
		((local_index++)) # indexing starts from zero for readme files
	fi

	if ! [ -d "$source" ] && [ -d "${destination%/*}" ]
	then
		tput setaf $SEVERITY_HIGH
		echo "source or destination does not exist!" >&2
		tput sgr0
		return 1
	fi

	if [ -d "$destination" ]
	then
		if mv "$source" "$destination"
		then
			sed -i "/^${source##*/}$/d" "${source%/*}/.index"
			if [ -n "$local_index" ]
			then
				sed -i "${local_index}i ${source##*/}" "${destination}/.index"
			else
				echo "${source##*/}" >> "${destination}/.index"
			fi
		else
			tput setaf $SEVERITY_HIGH
			echo "failed to move!" >&2
			tput sgr0
		fi
	else
		if mv "$source" "$destination"
		then
			sed -i "/^${source##*/}$/d" "${source%/*}/.index"
			if [ -n "$local_index" ]
			then
				sed -i "${local_index}i ${destination##*/}" "${destination%/*}/.index"
			else
				echo "${destination##*/}" >> "${destination%/*}/.index"
			fi
		else
			tput setaf $SEVERITY_HIGH
			echo "failed to move!" >&2
			tput sgr0
		fi

	fi
}

function swap_page {
	local location="${1%/*}"
	local source_index="${1}"
	local destination_index="${2}"

	if [ "${1%/*}" = "${2%/*}" ]
	then
		if [ -f "${location}/.index" ]
		then
			source_index="$(grep -n "${1##*/}" "${location}/.index")"
			destination_index="$(grep -n "${2##*/}" "${location}/.index")"
			sed -i "${destination_index}d" "${location}/.index"
			sed -i "${destination_index}i ${1##*/}" "${location}/.index"
			sed -i "${source_index}d" "${location}/.index"
			sed -i "${source_index}i ${2##*/}" "${location}/.index"
		else
			tput setaf $SEVERITY_HIGH
			echo "location not indexed: $location" >&2
			tput sgr0
			return 1
		fi
	else
		tput setaf $SEVERITY_HIGH
		echo "locations are not equal: $location" >&2
		tput sgr0
		return 1
	fi
}

function swap_chapter {
	local source="${1%/}"
	local destination="${2%/}"
	local source_index=
	local destination_index=
	
	if [ -d "$source" ] && [ -d "$destination" ]
	then
		source_index="$(grep -n "^${source##*/}$" "${source%/*}/.index")"
		source_index="${source_index%%:*}"
		((source_index--))
		destination_index="$(grep -n "^${destination##*/}$" "${destination%/*}/.index")"
		destination_index="${destination_index%%:*}"
		((destination_index--))

		if [ "${source%/*}" = "${destination%/*}" ]
		then
			sed -i "s/^${destination##*/}$/chapter_name_substitution/" "${destination%/*}/.index"
			sed -i "s/^${source##*/}$/${destination##*/}/" "${source%/*}/.index"
			sed -i "s/chapter_name_substitution/${source##*/}/" "${destination%/*}/.index"
		else
			move_chapter "$1" "./temporary_source_chapter"
			move_chapter "$2" "./temporary_destination_chapter"
			move_chapter "$PWD/temporary_source_chapter" "${destination%/*}" "$destination_index"
			move_chapter "$PWD/temporary_destination_chapter" "${source%/*}" "$source_index"
		fi
	else
		tput setaf $SEVERITY_HIGH
		echo "source or destination does not exist"
		tput sgr0
	fi
}

function remove_outputs {
	local directory=

	find -type f -name ".index" -exec sh -c '
		directory="{}"
		while read -r entry
		do
			if [ -f "${directory%/*}/${entry% *}" ]
			then
				touch "${directory%/*}/${entry% *}"
			fi
		done < "$directory"' \;
}

# requires path to page or chapter
function remove_files {
	if [ -f "./${1#\.\/}" ]
	then
		remove_page "./${1#\.\/}"
	else
		remove_chapter "./${1#\.\/}"
	fi
}

# requires path to source and destination
function move_files {
	local source="${1%/}"
	local destination="${2%/}"

	# source is a directory and destination doesn't have extension,
	if [ -d "${source}" ] && [ -z "$(sed -n 's/.*\.\([[:alnum:]]*\)$/\1/p' <<< "$destination")" ]
	then
		# locations exist
		if [ -d "${source%/*}" ] && [ -d "${destination%/*}" ]
		then
			# locations are similar
			if [ "${source%/*}" = "${destination%/*}" ]
			then
				# destination exists, swap chapter [move for now]
				if [ -d "$destination" ]
				then
					echo "moving chapter"
					move_chapter "$source" "$destination"
				# destination does not exist, rename chapter
				else
					rename_chapter "$source" "$destination"
				fi
			# locations are not similar
			else
				# destination exists, move chapter to destination
				if [ -d "$destination" ]
				then
					echo "moving chapter"
					move_chapter "$source" "$destination"
				# destination does not exist, move chapter to destination location and rename source with destination
				else
					echo "moving and renaming chapter"
					move_chapter "$source" "$destination"
				fi
			fi
		else
			tput setaf $SEVERITY_HIGH
			echo "invalid locations given:" >&2
			echo "  source: $source" >&2
			echo "  destination: $destination" >&2
			tput sgr0
			return 1
		fi
	# source is a file and destination has extension,
	elif [ -f "$source" ] && [ -n "$(sed -n 's/.*\.\([[:alnum:]]*\)$/\1/p' <<< "$destination")" ]
	then
		# locations are similar
		if [ "${source%/*}" = "${destination%/*}" ]
		then
			# destination exists, swap page
			if [ -f "$destination" ]
			then
				echo "swaping page"
				swap_page "$source" "$destination"
			# destination doesn't exist, rename page
			else
				rename_page "$source" "$destination"
			fi
		# locations are not similar
		else
			# destination exists, error cannot overwrite
			if [ -f "$destination" ]
			then
				tput setaf $SEVERITY_HIGH
				echo "destination exists, cannot overwrite." >&2
				tput sgr0
				return 1
			# destination doesn't exist, move page to destination
			else
			echo "moving page to: $destination"
				move_page "$source" "$destination"
			fi
		fi
	# source is a file and destination has extension,
	elif [ -f "$source" ] && [ -z "$(sed -n 's/.*\.\([[:alnum:]]*\)$/\1/p' <<< "$destination")" ]
	then
		# destination directory must exist
		if [ -d "${destination}" ]
		then
			echo "moving page to: $destination"
			move_page "$source" "$destination"
		else
			tput setaf $SEVERITY_HIGH
			echo "destination directory does not exist: $destination" >&2
			tput sgr0
			return 1
		fi
	# otherwise error invalid source
	else
		tput setaf $SEVERITY_HIGH
		echo "invalid destination: $destination" >&2
		tput sgr0
		return 1
	fi
}

# requires path
function reorder_index {
	local location="./${1/\.\//}"
	local item=
	local index_file=
	local new_index=

	if [ -f "$location" ]
	then
		index_file="${location%/*}/.index"
	elif [ -d "$location" ]
	then
		index_file="${location%/*}/.index"
	else
		tput setaf $SEVERITY_HIGH
		echo "invalid path: $location" >&2
		tput sgr0
		return 1
	fi

	if [ -f "$index_file" ] && [ "$(grep -c "^${1##*/}" "$index_file")" -gt 0 ]
	then
		PS3="Replace with: "
		select item in $(sed '1d' "$index_file" | xargs)
		do
			if [ -n "$item" ]
			then
				new_index="$REPLY"
				sed -i "/^${location##*/}$/d" "$index_file"
				sed -i "${new_index}a ${location##*/}" "$index_file"
				break
			else
				tput setaf $SEVERITY_HIGH
				echo "invalid number"
				tput sgr0
			fi
		done
	else
		tput setaf $SEVERITY_HIGH
		echo "not indexed: $1" >&2
		tput sgr0
		return 1
	fi
}

# requires path to chapter only
function list_index {
	echo "${1/\.\//}:"
	sed -n '2,$p' "${1%/}/.index" | nl
	echo
}

# requires relative path
function analyze_path {
	local path="${1%/}"
	local peek="${2:-false}"
	local extension="$(echo "$path" | sed -n 's/.*\.\([a-zA-Z]*\)$/\1/p')"

	# if does not have extension and exists and indexed: check all files within
	if [ -z "$extension" ] && [ -d "$path" ] && [ -f "${path%/*}/.index" ]\
		&& [ "$(grep -c "^${path##*/}$" "${path%/*}/.index")" -eq 1 ]
	then
		validate_chapter "$path"
		if [ "$peek" = "true" ]
		then
			list_index "$path"
		fi
	# if does not have extension and exists but not indexed: check and join
	elif [ -z "$extension" ] && [ -d "$path" ] && [ -f "${path%/*}/.index" ]\
		&& [ "$(grep -c "^${path##*/}$" "${path%/*}/.index")" -eq 0 ]
	then
		join_chapter "$path"
	# if does not have extension and does not exist: create chapter
	elif [ -z "$extension" ] && ! [ -d "$path" ]
	then
		add_chapter "$path"
	# if has extension and exists and indexed: check all files with it
	elif [ -n "$extension" ] && [ -f "$path" ] && [ -f "${path%/*}/.index" ]\
		&& [ "$(grep -c "^${path##*/}$" "${path%/*}/.index")" -eq 1 ]
	then
		validate_page "$path"
	# if has extension and exists but is not indexed: check and join practice
	elif [ -n "$extension" ] && [ -f "$path" ] && [ -f "${path%/*}/.index" ]\
		&& [ "$(grep -c "^${path##*/}$" "${path%/*}/.index")" -eq 0 ]
	then
		join_page "$path"
	# if has extension but does not exist, create practice page
	elif [ -n "$extension" ] && ! [ -f "$path" ]
	then
		add_page "$path"
	# otherwise, unhandled error
	else
		return 1
	fi
}

function analyze_paramters {
	local source="${1#\.\/}"
	local destination="$2"

	if [ "$source" = "." ]
	then
		if [ -f "./.index" ]
		then
			list_index "."
			return 0
		else
			tput setaf $SEVERITY_HIGH
			echo "practice directory not initialized yet"
			echo "run \`${0##*/} --help\`"
			tput sgr0
			return 1
		fi
	fi

	if [ -z "$destination" ]
	then
		local hierarchy="."
		local entry=
		local peek=
		for entry in ${source//\//$'\n'}
		do
			hierarchy+="/$entry"

			# peek index of chapter if nothing happens
			if [ "${hierarchy}" = "./${1%/}" ]
			then
				peek=true
			else
				peek=false
			fi

			if ! analyze_path "${hierarchy/$PWD/}" "$peek"
			then
				tput setaf $SEVERITY_HIGH
				echo "analyzing path failed: $path" >&2
				tput sgr0
			fi
		done
	else
		if ! move_files "./${1#\.\/}" "./${2#\.\/}"
		then
			tput setaf $SEVERITY_HIGH
			echo "operation failed: $source" >&2
			tput sgr0
		fi
	fi
}

# Analyze Options and Paramters
###############################################################################

if [ -f ./.config ] && [ ./.index ]
then
	validation_check=202101202003
	source ./.config
	if [ "${VALIDATION_ID:-0}" -lt "$validation_check" ]
	then
		tput setaf $SEVERITY_LOW
		echo "configuring repository for the latest update..." >&2
		tput sgr0
		if ! validate_configuration "./.index"
		then
			echo "configuration failed"
			exit 1
		fi
		regenerate_configuration "./.config"
		extract_configuration "./.config"
		sed -i "s/^\(VALIDATION_ID=\)[0-9]*$/\1${validation_check}/" ./.config
		echo
		echo "configuration complete"
		echo "run again to continue"
		exit 0
	fi
fi

if [ $# -eq 0 ]
then
	# At least one .index must exist at current directory
	# Everything starts here
	generate_manuals "./.index"
else
	case "$1" in
		-h|--help) usage ;;
		-r|--remove) remove_files "${2%/}" ;;
		-o|--reorder) reorder_index "${2%/}" ;;
		-f|--force-compile) remove_outputs; generate_manuals "./.index" ;;
		*)
			if [ "${1:0:1}" = "-" ]
			then
				usage
			else
				if ! analyze_paramters "$1" "$2"
				then
					exit 1
				fi
			fi ;;
	esac
fi
