#!/usr/bin/env bash

psql -U postgres -d flashback -f "$( readlink -f "$(dirname "$0")/.." )/design/users.sql"
psql -U postgres -d flashback -f "$( readlink -f "$(dirname "$0")/.." )create-note.sql"
psql -U postgres -d flashback -f "$( readlink -f "$(dirname "$0")/.." )create-resource.sql"

return
psql -U postgres -d flashback -f "$( readlink -f "$(dirname "$0")/.." )add-note-block.sql"
psql -U postgres -d flashback -f "$( readlink -f "$(dirname "$0")/.." )add-note-reference.sql"
psql -U postgres -d flashback -f "$( readlink -f "$(dirname "$0")/.." )add-practice-block.sql"
psql -U postgres -d flashback -f "$( readlink -f "$(dirname "$0")/.." )add-practice-reference.sql"
psql -U postgres -d flashback -f "$( readlink -f "$(dirname "$0")/.." )create-practice.sql"
psql -U postgres -d flashback -f "$( readlink -f "$(dirname "$0")/.." )edit-note-block.sql"
psql -U postgres -d flashback -f "$( readlink -f "$(dirname "$0")/.." )edit-note-heading.sql"
psql -U postgres -d flashback -f "$( readlink -f "$(dirname "$0")/.." )edit-practice-block.sql"
psql -U postgres -d flashback -f "$( readlink -f "$(dirname "$0")/.." )edit-practice-headline.sql"
psql -U postgres -d flashback -f "$( readlink -f "$(dirname "$0")/.." )get-user-practices.sql"
psql -U postgres -d flashback -f "$( readlink -f "$(dirname "$0")/.." )get-user-studies.sql"
psql -U postgres -d flashback -f "$( readlink -f "$(dirname "$0")/.." )merge-duplicate-resources.sql"
psql -U postgres -d flashback -f "$( readlink -f "$(dirname "$0")/.." )merge-note-blocks.sql"
psql -U postgres -d flashback -f "$( readlink -f "$(dirname "$0")/.." )merge-practice-blocks.sql"
psql -U postgres -d flashback -f "$( readlink -f "$(dirname "$0")/.." )remove-note-reference.sql"
psql -U postgres -d flashback -f "$( readlink -f "$(dirname "$0")/.." )remove-reference-from-practice.sql"
psql -U postgres -d flashback -f "$( readlink -f "$(dirname "$0")/.." )rename-resource.sql"
psql -U postgres -d flashback -f "$( readlink -f "$(dirname "$0")/.." )rename-section-headline.sql"
psql -U postgres -d flashback -f "$( readlink -f "$(dirname "$0")/.." )rename-subject.sql"
psql -U postgres -d flashback -f "$( readlink -f "$(dirname "$0")/.." )rename-topic.sql"
psql -U postgres -d flashback -f "$( readlink -f "$(dirname "$0")/.." )split-note-block.sql"
psql -U postgres -d flashback -f "$( readlink -f "$(dirname "$0")/.." )split-practice-block.sql"
psql -U postgres -d flashback -f "$( readlink -f "$(dirname "$0")/.." )users.sql"
