#!/usr/bin/env bash

STORAGE_PATH="${STORAGE_PATH:-/home/brian/projects/references/books}"

trap "stop_shell" SIGINT

function stop_shell() {
    echo -e "\b\bsaving process..."
    exit
}

for resource in "$STORAGE_PATH"/*
do
    chapter_scope=0
    body_scope=0
    resource_scope=0
    chapter=

    resource_begin="$(sed -n '1,/^## /=' "$resource" | tail -n2 | head -n1)"

    echo -e "\e[1;35m>>> $(sed -n '1s/^# \[\([^)]\+\)\].*/\1/p' "$resource")\e[0m"

    while read -r line
    do
        if [ "$line" == "<details>" ]
        then
            if [ "$resource_scope" -eq 1 ]
            then
                echo -e "\e[1;33m"'<<< wrap up practice'"\e[0m"
            fi

            resource_scope=0; echo -ne "\e[0m"
            body_scope=1; echo -e "\e[1;32m"'>>> body begin'"\e[0m"
        elif [ "$line" == "</details>" ]
        then
            body_scope=0; echo -e "\e[1;31m"'<<< body end'"\e[0m"
            resource_scope=1; echo -ne "\e[1;34m"
        elif [ "${line:0:9}" == "<summary>" ]
        then
            echo -e "\e[1;36m""${line:9:-10}""\e[0m"
            read -r # get rid of next empty line
        elif [ "${line:0:3}" == "## " ]
        then
            if [ "$body_scope" -eq 1 ] || [ "$resource_scope" -eq 1 ]
            then
                body_scope=0; echo -e "\e[1;33m"'<<< wrap up practice'"\e[0m"
            fi

            resource_scope=0; echo -ne "\e[0m"

            if [ "$chapter_scope" -eq 0 ]
            then
                chapter="${line#*Chapter }"
                chapter_scope=1
                echo -e "\e[1;37m"">>> beginning of chapter $chapter""\e[0m"
            else
                echo -e "\e[1;37m""<<< end of chapter $chapter""\e[0m\n"
                chapter="${line#*Chapter }"
                echo -e "\e[1;37m"">>> beginning of chapter $chapter""\e[0m"
            fi
        elif [ "${#line}" -eq 0 ] && [ "$body_scope" -eq 0 ]
        then
            continue
        else
            echo "$line"
        fi
    done <<< "$(sed "1,${resource_begin}d" "$resource")"

    if [ "$resource_scope" -eq 1 ]
    then
        resource_scope=0; echo -ne "\e[0m"
    fi

    if [ "$body_scope" -eq 1 ]
    then
        body_scope=0; echo -e "\e[1;33m"'<<< wrap up practice'"\e[0m"
    fi

    if [ "$chapter_scope" -eq 1 ]
    then
        chapter_scope=0; echo -e "\e[1;37m""<<< end of chapter $chapter""\e[0m"
    fi

    echo -e "\e[1;35m"'<<< resource end'"\e[0m\n"
done
